### ISSUE TITLE
error convert y4m to m4v  bt709

### ISSUE THREAD

**Issue by tamntaptech1** [mdejong/AlphaOverVideo#2]
After i'm convert png sequence with command
srgb_to_bt709 -alpha 1 -frames F0001.png -fps 30 LightDance.y4m
I convert y4m to m4v use : 
ext_ffmpeg_encode_srgb_crf.sh LightDance.y4m LightDance.m4v 23

Has issue : 
ffmpeg -y -i LightDance.y4m -c:v libx264 -pix_fmt yuv420p -preset:v slow -profile:v main -tune:v animation -crf 23 -color_primaries bt709 -color_trc iec61966_2_1 -colorspace bt709 LightDance.m4v
ffmpeg version 1.2.3 Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 29 2013 00:13:55 with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Users/mo/Development/FFMpegMac/install --arch=x86_64 --as=yasm --disable-shared --enable-static --enable-gpl --enable-pthreads --enable-version3 --enable-libx264 --enable-avfilter --enable-filters --enable-runtime-cpudetect
  libavutil      52. 18.100 / 52. 18.100
  libavcodec     54. 92.100 / 54. 92.100
  libavformat    54. 63.104 / 54. 63.104
  libavdevice    54.  3.103 / 54.  3.103
  libavfilter     3. 42.103 /  3. 42.103
  libswscale      2.  2.100 /  2.  2.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  2.100 / 52.  2.100
[yuv4mpegpipe @ 0x7fc3fa815c00] Estimating duration from bitrate, this may be inaccurate
Input #0, yuv4mpegpipe, from 'LightDance.y4m':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1024x1024, SAR 1:1 DAR 1:1, 24 tbr, 24 tbn, 24 tbc
[NULL @ 0x7fc3fa826e00] [Eval @ 0x7ffedfd9ad60] Undefined constant or missing '(' in 'bt709'
[NULL @ 0x7fc3fa826e00] Unable to parse option value "bt709"
[NULL @ 0x7fc3fa826e00] Error setting option color_primaries to value bt709.
Output #0, ipod, to 'LightDance.m4v':
    Stream #0:0: Video: none, yuv420p, 1024x1024 [SAR 1:1 DAR 1:1], q=-1--1, 90k tbn, 24 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo -> libx264)
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by tamntaptech1** [comment]
Upgrade FFmpeg version

**Comment by mdejong** [comment]
If you want to build your own static version of ffmpeg from source code, here is a shell script that does just that.

(download the packages into a directory and then save this file as run build.sh)
```
# This build script will configure and build a static version of
# ffmpeg with x264 support compiled in. This version does not attempt
# to build in optional audio components like AAC, the focus here is
# on a version of ffmpeg that can encode H264 via the x264 library.

export CC=clang

# Mac 64 bit ABI
FFMPEG_ARCH=x86_64

BUILD=`pwd`/build
TARGET=`pwd`/install
PACKAGES=`pwd`

rm -rf $BUILD
mkdir $BUILD
rm -rf $TARGET
mkdir $TARGET

export PATH=${TARGET}/bin:$PATH 

# -----------------------------------------------------

# Nasm : https://www.nasm.us/

NASM=nasm-2.14
NASM_TAR=${PACKAGES}/${NASM}.tar.bz2

echo "build $NASM"
cd $BUILD
tar -xzf $NASM_TAR
cd $NASM

# Note that yasm will build a static library by default
./configure --prefix=${TARGET}
make
make install

# -----------------------------------------------------

# x264 : http://www.videolan.org/developers/x264.html
X264=x264-snapshot
X264_TAR=${PACKAGES}/x264-snapshot-20181222-2245-stable.tar.bz2

echo "build $X264"
cd $BUILD
tar -xzf $X264_TAR
mv x264-snapshot-* $X264
cd $X264

# Build x264 as a static library

./configure --prefix=${TARGET} \
--enable-static \
--disable-opencl

make
make install
make install-lib-static

# -----------------------------------------------------

# FFMPEG : http://ffmpeg.org/download.html

echo "build FFMPEG"

FFMPEG=ffmpeg-4.1
FFMPEG_TAR=${PACKAGES}/${FFMPEG}.tar.bz2

cd $BUILD
tar -xzf $FFMPEG_TAR
mv $FFMPEG ${FFMPEG}-src
mkdir $FFMPEG
cd $FFMPEG

# Build ffmpeg as static library and build in support for
# yasm and x264

export LDFLAGS="-L${TARGET}/lib" 
export CFLAGS="-I${TARGET}/include"

../${FFMPEG}-src/configure --prefix=${TARGET} \
--arch=${FFMPEG_ARCH} \
--as=yasm \
--disable-shared \
--enable-static \
--enable-gpl \
--enable-pthreads \
--enable-version3 \
--enable-libx264 \
--enable-avfilter \
--enable-filters \
--enable-runtime-cpudetect

# --disable-stripping
# --disable-optimizations
# --disable-mmx

make
make install

# Done

cd $TARGET/bin

echo "installed ffmpeg binary in `pwd`"
ls -la ffmpeg

```

**Comment by tamntaptech1** [comment]
Thanks mdejong for help.
